"""initial operational schema

Revision ID: 0001
Revises:
Create Date: 2026-09-01 23:26:26.125142
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operational_events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operational_events_aggregate_id"),
        "operational_events",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_events_aggregate_type"),
        "operational_events",
        ["aggregate_type"],
        unique=False,
    )
    op.create_table(
        "policy_versions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "policies",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash", name="uq_policy_content_hash"),
        sa.UniqueConstraint("version", name="uq_policy_version_number"),
    )
    op.create_table(
        "red_experiment_configs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash", name="uq_red_config_content_hash"),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "targets",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "work_leases",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_leases_status"), "work_leases", ["status"], unique=False)
    op.create_table(
        "target_versions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=False),
        sa.Column("image_digest", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_target_versions_image_digest"), "target_versions", ["image_digest"], unique=False
    )
    op.create_index(
        op.f("ix_target_versions_target_id"), "target_versions", ["target_id"], unique=False
    )
    op.create_table(
        "attack_tasks",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("target_version_id", sa.String(length=80), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_version_id"],
            ["target_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attack_tasks_target_version_id"),
        "attack_tasks",
        ["target_version_id"],
        unique=False,
    )
    op.create_table(
        "target_manifests",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("target_version_id", sa.String(length=80), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_version_id"],
            ["target_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_version_id"),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("target_version_id", sa.String(length=80), nullable=False),
        sa.Column("attack_task_id", sa.String(length=80), nullable=False),
        sa.Column("policy_version_id", sa.String(length=80), nullable=True),
        sa.Column("search_mode", sa.String(length=20), nullable=False),
        sa.Column("replay_episode_id", sa.String(length=80), nullable=True),
        sa.Column("run_kind", sa.String(length=40), nullable=False),
        sa.Column("source_finding_id", sa.String(length=80), nullable=True),
        sa.Column("source_episode_id", sa.String(length=80), nullable=True),
        sa.Column("red_config_id", sa.String(length=80), nullable=True),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("cancellation_requested", sa.Boolean(), nullable=False),
        sa.Column("episodes_started", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("cost_used", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attack_task_id"],
            ["attack_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["red_config_id"],
            ["red_experiment_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_version_id"],
            ["target_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaigns_target_version_id"), "campaigns", ["target_version_id"], unique=False
    )
    op.create_table(
        "episodes",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("campaign_id", sa.String(length=80), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("cumulative_reward", sa.Float(), nullable=False),
        sa.Column("terminal_success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_episodes_campaign_id"), "episodes", ["campaign_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("campaign_id", sa.String(length=80), nullable=True),
        sa.Column("episode_id", sa.String(length=80), nullable=True),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("uri", sa.String(length=1000), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("parent_artifact_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_artifact_id"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "episode_steps",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("episode_id", sa.String(length=80), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column(
            "red_action",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "public_observation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("reward", sa.Float(), nullable=False),
        sa.Column("terminal_success", sa.Boolean(), nullable=False),
        sa.Column("strategy_id", sa.String(length=80), nullable=True),
        sa.Column("model_invocation_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("episode_id", "step_index", name="uq_episode_step"),
    )
    op.create_index(
        op.f("ix_episode_steps_episode_id"), "episode_steps", ["episode_id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("campaign_id", sa.String(length=80), nullable=False),
        sa.Column("episode_id", sa.String(length=80), nullable=False),
        sa.Column("verifier_id", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.Float(), nullable=False),
        sa.Column("evidence_artifact_id", sa.String(length=80), nullable=True),
        sa.Column("policy_version_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_campaign_id"), "findings", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_findings_episode_id"), "findings", ["episode_id"], unique=False)
    op.create_table(
        "trajectory_summaries",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("episode_id", sa.String(length=80), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trajectory_summaries_episode_id"),
        "trajectory_summaries",
        ["episode_id"],
        unique=False,
    )
    op.create_table(
        "verifier_events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("episode_id", sa.String(length=80), nullable=False),
        sa.Column("verifier_id", sa.String(length=100), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verifier_events_episode_id"), "verifier_events", ["episode_id"], unique=False
    )
    op.create_table(
        "effect_attempts",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("episode_id", sa.String(length=80), nullable=False),
        sa.Column("step_id", sa.String(length=80), nullable=True),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["episode_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_effect_attempts_episode_id"), "effect_attempts", ["episode_id"], unique=False
    )
    op.create_table(
        "hardening_runs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("finding_id", sa.String(length=80), nullable=False),
        sa.Column("policy_version_id", sa.String(length=80), nullable=False),
        sa.Column("exact_replay_campaign_id", sa.String(length=80), nullable=True),
        sa.Column("bypass_campaign_id", sa.String(length=80), nullable=True),
        sa.Column("benign_campaign_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("artifact_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["benign_campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bypass_campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exact_replay_campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hardening_runs_finding_id"), "hardening_runs", ["finding_id"], unique=False
    )
    op.create_table(
        "model_invocations",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("campaign_id", sa.String(length=80), nullable=False),
        sa.Column("episode_id", sa.String(length=80), nullable=True),
        sa.Column("step_id", sa.String(length=80), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["episode_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_invocations_campaign_id"), "model_invocations", ["campaign_id"], unique=False
    )
    op.create_table(
        "policy_decisions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("effect_id", sa.String(length=80), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["effect_id"],
            ["effect_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_decisions_effect_id"), "policy_decisions", ["effect_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_decisions_effect_id"), table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_model_invocations_campaign_id"), table_name="model_invocations")
    op.drop_table("model_invocations")
    op.drop_index(op.f("ix_hardening_runs_finding_id"), table_name="hardening_runs")
    op.drop_table("hardening_runs")
    op.drop_index(op.f("ix_effect_attempts_episode_id"), table_name="effect_attempts")
    op.drop_table("effect_attempts")
    op.drop_index(op.f("ix_verifier_events_episode_id"), table_name="verifier_events")
    op.drop_table("verifier_events")
    op.drop_index(op.f("ix_trajectory_summaries_episode_id"), table_name="trajectory_summaries")
    op.drop_table("trajectory_summaries")
    op.drop_index(op.f("ix_findings_episode_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_campaign_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_episode_steps_episode_id"), table_name="episode_steps")
    op.drop_table("episode_steps")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_episodes_campaign_id"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_index(op.f("ix_campaigns_target_version_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("target_manifests")
    op.drop_index(op.f("ix_attack_tasks_target_version_id"), table_name="attack_tasks")
    op.drop_table("attack_tasks")
    op.drop_index(op.f("ix_target_versions_target_id"), table_name="target_versions")
    op.drop_index(op.f("ix_target_versions_image_digest"), table_name="target_versions")
    op.drop_table("target_versions")
    op.drop_index(op.f("ix_work_leases_status"), table_name="work_leases")
    op.drop_table("work_leases")
    op.drop_table("targets")
    op.drop_table("strategies")
    op.drop_table("red_experiment_configs")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_operational_events_aggregate_type"), table_name="operational_events")
    op.drop_index(op.f("ix_operational_events_aggregate_id"), table_name="operational_events")
    op.drop_table("operational_events")
    # ### end Alembic commands ###
